#server:
#  port: 4040
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql://localhost:3306/jwt
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: "update"
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#  main:
#    allow-circular-references: true
#


#server:
#  port: 8080
#spring:
#  datasource:
#    password: root
#    url: jdbc:mysql://localhost:3306/jwt
#    username: root
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true